create table T1_2024 (
	`DATA` date,
    REG_ANS varchar(6),
    CD_CONTA_CONTABIL varchar(255),
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL DECIMAL(15,2),
    VL_SALDO_FINAL DECIMAL(15,2)
);

create table T2_2024 (
	`DATA` date,
    REG_ANS varchar(6),
    CD_CONTA_CONTABIL varchar(255),
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL DECIMAL(15,2),
    VL_SALDO_FINAL DECIMAL(15,2)
);

create table T3_2024 (
	`DATA` date,
    REG_ANS varchar(6),
    CD_CONTA_CONTABIL varchar(255),
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL DECIMAL(15,2),
    VL_SALDO_FINAL DECIMAL(15,2)
);

create table T4_2024 (
	`DATA` date,
    REG_ANS varchar(6),
    CD_CONTA_CONTABIL varchar(255),
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL DECIMAL(15,2),
    VL_SALDO_FINAL DECIMAL(15,2)
);

