create table T1_2024 (
	`DATA` date NOT NULL,
    REG_ANS varchar(6) NOT NULL,
    CD_CONTA_CONTABIL varchar(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    VL_SALDO_INICIAL DECIMAL(15,2) NOT NULL,
    VL_SALDO_FINAL DECIMAL(15,2) NOT NULL
);

create table T2_2024 (
	`DATA` date NOT NULL,
    REG_ANS varchar(6) NOT NULL,
    CD_CONTA_CONTABIL varchar(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    VL_SALDO_INICIAL DECIMAL(15,2) NOT NULL,
    VL_SALDO_FINAL DECIMAL(15,2) NOT NULL
);

create table T3_2024 (
	`DATA` date NOT NULL,
    REG_ANS varchar(6) NOT NULL,
    CD_CONTA_CONTABIL varchar(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    VL_SALDO_INICIAL DECIMAL(15,2) NOT NULL,
    VL_SALDO_FINAL DECIMAL(15,2) NOT NULL
);

create table T4_2024 (
	`DATA` date NOT NULL,
    REG_ANS varchar(6) NOT NULL,
    CD_CONTA_CONTABIL varchar(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    VL_SALDO_INICIAL DECIMAL(15,2) NOT NULL,
    VL_SALDO_FINAL DECIMAL(15,2) NOT NULL
);

